packages:
  - 'packages/*'
allowBuilds:
  cypress: true
minimumReleaseAgeExclude:
  - '@fate-core/mod-types@0.1.0'
onlyBuiltDependencies:
  - core-js
  - cypress
  - esbuild
# Audit temporary overrides
overrides:
  nanoid: 3.3.18
  postcss: 8.5.23
